### ISSUE TITLE
Question: Is there a way to use your tool to convert WDL to CWL format

### ISSUE THREAD

**Issue by michael-kotliar** [PMCC-BioinformaticsCore/janis-core#76]
Not an actual issue, just a question. Is there any way to use your tool to convert WDL into CWL format? Or, at least, parse WDL into some objects that are compatible with source code from cwltool?

Thanks!

**Comment by illusional** [comment]
Hey @michael-kotliar! I've been working on a WDL parser in #69, it's not wrapped up nicely yet in the tool suite, but you could use it to convert some workflows:

Here's a direct link to the script: https://raw.githubusercontent.com/PMCC-BioinformaticsCore/janis-core/add-from-wdl/janis_core/ingestion/fromwdl.py
You'll have to have janis-core + MiniWDL installed, you could change the last line (L447) to translate`"cwl"` instead of `"janis"`, and then run the script directly:

```shell
python3 fromwdl.py <yourscript.wdl>
```

**Comment by michael-kotliar** [comment]
Hi @illusional,
Great! Thanks for the script!

**Comment by illusional** [comment]
How'd you go @michael-kotliar?

**Comment by michael-kotliar** [comment]
It works fine. I tested it with a simple WDL workflow that I had and I was able to run it with cwltool. I think I had to make some changes in the code to generate outputs, but for now, I anyway use it only for testing purposes. However, I hope that this script will evolve and will cover more features from WDL:)
